// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Removing the above comment will disable type generation for this module
// This file was created by @hubspot/cms-dev-server, for more information see https://github.hubspot.com/cms-react/reference/js-modules.html#module-fields
import { type TextFieldType, type RequiredField, type ImageFieldType, type RichTextFieldType, type DefaultValues } from "@hubspot/cms-components/fields";
type EventInfoCardFieldsType = DefaultValues<{
    title: RequiredField<TextFieldType>;
    image?: ImageFieldType;
    bodyDetailsLeft: RequiredField<RichTextFieldType>;
    bodyDetailsRight: RequiredField<RichTextFieldType>;
    extraInfo: RequiredField<TextFieldType>;
    badge: RequiredField<TextFieldType>;
    backgroundColor?: "bg-grey-200" | "bg-white";
}>;
export default EventInfoCardFieldsType;