// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Removing the above comment will disable type generation for this module
// This file was created by @hubspot/cms-dev-server, for more information see https://github.hubspot.com/cms-react/reference/js-modules.html#module-fields
import { type ImageFieldType, type TextFieldType, type LinkFieldType, type BooleanFieldType, type RepeaterGroup, type DefaultValues } from "@hubspot/cms-components/fields";
type FooterFieldsType = DefaultValues<{
    logo?: ImageFieldType;
    footerColumns: RepeaterGroup<{
        title?: TextFieldType;
        link?: LinkFieldType;
        persistOnMobile?: BooleanFieldType;
        items: RepeaterGroup<{
            text?: TextFieldType;
            type?: "link" | "boldLink" | "heading" | "text" | "image" | "socialLinks";
            link?: LinkFieldType;
            boldLink?: LinkFieldType;
            image?: ImageFieldType;
            socialLinks: RepeaterGroup<{
                link?: LinkFieldType;
                image?: ImageFieldType;
            }>;
        }>;
    }>;
}>;
export default FooterFieldsType;