// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Removing the above comment will disable type generation for this module
// This file was created by @hubspot/cms-dev-server, for more information see https://github.hubspot.com/cms-react/reference/js-modules.html#module-fields
import { type TextFieldType, type RequiredField, type LinkFieldType, type RepeaterGroup, type RichTextFieldType, type DefaultValues } from "@hubspot/cms-components/fields";
type EcommProductListingPreviewFieldsType = DefaultValues<{
    details?: TextFieldType;
    productHelpText: RequiredField<TextFieldType>;
    products: RepeaterGroup<{
        categoryCode?: TextFieldType;
        productTheme?: "orange" | "sky" | "green";
        tagLine: RequiredField<TextFieldType>;
        productName: RequiredField<TextFieldType>;
        link?: LinkFieldType;
    }>;
    note: RequiredField<RichTextFieldType>;
}>;
export default EcommProductListingPreviewFieldsType;